changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Fixed Problems
      labels:
        - bug-fix
    - title: Other Changes
      labels:
        - "*"
