version: 2
build:
    image: latest
conda:
    environment: docs/environment.yml
sphinx:
    builder: html
    configuration: docs/conf.py
python:
    version: 3.8
    install:
    - requirements: docs/rtd-requirements.txt
