version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "3.9"

sphinx:
    configuration: docs/rtd-conf.py

python:
    install:
        - method: pip
          path: doxyrest

conda:
    environment: docs/rtd-conda-env.yml
