version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "3.8"

sphinx:
    configuration: doc/conf.py

python:
    install:
        - requirements: doc/rtd-requirements.txt

conda:
    environment: docs/environment.yml
