version: 2

build:
    os: ubuntu-20.04
    apt_packages:
        - doxygen
        - cmake

sphinx:
    configuration: doc/conf.py

python:
    version: "3.8"
    install:
        - method: pip
          path: .
