name: build-env

env:
  PETSC_VERSION: 3.17.0
  PETSC_ARCH: arch-godzilla-c-opt
  PETSC_CACHE_NUM: 9

on: [workflow_dispatch]

jobs:
  build-env:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc
          - os: ubuntu-22.04
            compiler: clang
          - os: macos-10.15
            compiler: clang
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -qq
          sudo apt install llvm-12 libblas-dev liblapack-dev
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: brew install automake
      - name: Setup env (C/C++)
        if: startsWith(matrix.os, 'ubuntu') && matrix.compiler == 'clang'
        run: |
          echo "CC=clang-12" >> $GITHUB_ENV
          echo "CXX=clang++-12" >> $GITHUB_ENV
      - name: Setup env (C/C++)
        if: startsWith(matrix.os, 'ubuntu') && matrix.compiler == 'gcc'
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
      - name: Setup env (C/C++)
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Setup env (fortran)
        run: |
          echo "FC=gfortran-10" >> $GITHUB_ENV
      - name: Cache PETSc
        id: cache-petsc
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/petsc
          key: ${{ runner.os }}-${{ matrix.compiler }}-petsc-cache-${{ env.PETSC_CACHE_NUM }}
      - name: Build PETSc
        run: |
          cd ${{ github.workspace }}
          wget -q https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-${PETSC_VERSION}.tar.gz
          tar -xzf petsc-${PETSC_VERSION}.tar.gz
          cd petsc-${PETSC_VERSION}
          echo "::group::configure"
          ./configure \
            --prefix=${{ github.workspace }}/petsc \
            --shared-libraries \
            --with-debugging=no \
            --with-cxx-dialect=cxx14 \
            --with-pic=yes \
            --with-ssl=no \
            --download-cmake \
            --download-mpich \
            --download-exodusii \
            --download-netcdf \
            --download-pnetcdf \
            --download-hdf5 \
            --download-zlib \
            --CC=$CC \
            --CXX=$CXX \
            --FC=$FC \
            PETSC_DIR=`pwd`
          echo "::endgroup::"
          echo "::group::make"
          make PETSC_DIR=`pwd` all
          make PETSC_DIR=`pwd` install
          echo "::endgroup::"
      - name: Upload configure.log
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.job }}-configure.log
          path: ${{ github.workspace }}/petsc-${{ env.PETSC_VERSION }}/configure.log
