name: clang-tidy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  clang-tidy:
    name: Static analysis (clang-tidy)
    runs-on: ubuntu-22.04
    env:
      PETSC_VERSION: 3.17.0
      PETSC_CACHE_NUM: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: main

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install \
            cmake \
            libblas-dev \
            liblapack-dev \
            libfmt-dev \
            libyaml-cpp-dev \
            zlib1g-dev

      - name: Install clang-tidy
        run: |
          sudo apt-get install -y clang-tidy

      - name: Setup env
        run: |
          echo "${{ github.workspace }}/petsc/bin" >> $GITHUB_PATH
          echo "PETSC_DIR=${{ github.workspace }}/petsc" >> $GITHUB_ENV
          echo "NETCDF_DIR=${{ github.workspace }}/petsc" >> $GITHUB_ENV
          echo "EXODUSII_DIR=${{ github.workspace }}/petsc" >> $GITHUB_ENV
          echo "CC=mpicc" >> $GITHUB_ENV
          echo "CXX=mpicxx" >> $GITHUB_ENV

      - name: Cache PETSc
        id: cache-petsc
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/petsc
          key: ${{ runner.os }}-gcc-petsc-cache-${{ env.PETSC_CACHE_NUM }}
          restore-keys: ${{ runner.os }}-gcc-petsc-cache-${{ env.PETSC_CACHE_NUM }}

      - name: Prepare compile_commands.json
        run: |
          cmake -S ${{ github.workspace }}/main -B ${{ github.workspace }}/main/build \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Create results directory
        run: |
          mkdir clang-tidy-result

      - name: Analyze
        run: |
          git -C ${{ github.workspace }}/main diff -U0 HEAD^ | clang-tidy-diff -p1 -path ${{ github.workspace }}/main/build -export-fixes clang-tidy-result/fixes.yml

      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@master
        with:
          clang_tidy_fixes: clang-tidy-result/fixes.yml
          request_changes: true
          suggestions_per_comment: 10
