name: github-pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-22.04
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          auto-update-conda: false
          channels: andrsd,defaults

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          conda install \
            cmake \
            make \
            mpich-mpicxx \
            mpicpp-lite=2.* \
            spdlog=1.* \
            h5pp==1.11.* \
            doxygen \
            sphinx \
            sphinx_rtd_theme \
            breathe==4.35.0 \
            sphinx-design \
            fmt=11.* \
            petsc==3.22.* \
            yaml-cpp==0.8.0 \
            exodusIIcpp=3.* \
            teciocpp \
            pyyaml

      - name: Build doco
        run: |
          cmake -S . -B ${{ github.workspace }}/build
          make -C ${{ github.workspace }}/build doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/build/docs/html
