name: github-pages

env:
  PETSC_CACHE_NUM: 10
  EXODUSIICPP_VERSION: 1.6

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install \
            doxygen \
            python3-sphinx \
            python3-sphinx-rtd-theme \
            python3-breathe \
            python3-sphinx-tabs \
            libblas-dev \
            liblapack-dev \
            libfmt-dev \
            libyaml-cpp-dev \
            zlib1g-dev

      - name: Set up env
        run: |
          echo "${{ github.workspace }}/petsc/bin" >> $GITHUB_PATH
          echo "NETCDF_DIR=${{ github.workspace }}/petsc" >> $GITHUB_ENV
          echo "EXODUSII_DIR=${{ github.workspace }}/petsc" >> $GITHUB_ENV
          echo "PETSC_DIR=${{ github.workspace }}/petsc" >> $GITHUB_ENV
          echo "CC=mpicc" >> $GITHUB_ENV
          echo "CXX=mpicxx" >> $GITHUB_ENV

      - name: Cache PETSc
        id: cache-petsc
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/petsc
          key: ${{ runner.os }}-gcc-petsc-cache-${{ env.PETSC_CACHE_NUM }}
          restore-keys: ${{ runner.os }}-gcc-petsc-cache-${{ env.PETSC_CACHE_NUM }}

      - name: Build exodusIIcpp
        run: |
          cd ${{ github.workspace }}
          echo "::group::download"
          wget -q https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v${EXODUSIICPP_VERSION}.tar.gz -O exodusIIcpp-${EXODUSIICPP_VERSION}.tar.gz
          tar -xzf exodusIIcpp-${EXODUSIICPP_VERSION}.tar.gz
          echo "::endgroup::"
          echo "::group::configure"
          cmake \
            -S ${{ github.workspace }}/exodusIIcpp-${EXODUSIICPP_VERSION} \
            -B ${{ github.workspace }}/exodusIIcpp-${EXODUSIICPP_VERSION}/build \
            -DCMAKE_BUILD_TYPE=Release \
            -DEXODUSIICPP_LIBRARY_TYPE=SHARED
          echo "::endgroup::"
          echo "::group::make"
          cd ${{ github.workspace }}/exodusIIcpp-${EXODUSIICPP_VERSION}/build
          make all -C ${{ github.workspace }}/exodusIIcpp-${EXODUSIICPP_VERSION}/build
          sudo make install -C ${{ github.workspace }}/exodusIIcpp-${EXODUSIICPP_VERSION}/build
          echo "::endgroup::"

      - name: Build doco
        run: |
          cmake -S . -B ${{ github.workspace }}/build
          make -C ${{ github.workspace }}/build doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/build/docs/html
